CREATE TABLE IF NOT EXISTS `TB_GENDER` (
    `ID` int NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `NAME` varchar(10) NOT NULL,
)ENGINE=InnoDB DEFAULT CHARSET=UTF8;

CREATE TABLE IF NOT EXISTS `TB_PERSON` (
    `ID` int NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `ID_GENDER` int NOT NULL,
    `FULL_NAME` varchar(50) NOT NULL,
    `BIRTHDATE` timestamp,
    foreign key (ID_GENDER) references TB_GENDER(ID)

)ENGINE=InnoDB DEFAULT CHARSET=UTF8;